// Configuração de depoimentos para a tela inicial
export const INITIAL_TESTIMONIALS = [
  {
    id: 101,
    name: "Ana Oliveira",
    message: "Comecei a vender brigadeiros gourmet e já estou faturando R$1.800 por mês!",
    time: "agora",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 102,
    name: "Carla Mendes",
    message: "Fiz R$350 no meu primeiro final de semana vendendo bolos no pote!",
    time: "2 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 103,
    name: "Beatriz Santos",
    message: "Meus doces sem forno são os mais pedidos nas festas da cidade!",
    time: "5 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 104,
    name: "Daniela Costa",
    message: "Larguei meu emprego e agora ganho 3x mais com confeitaria em casa!",
    time: "10 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 105,
    name: "Fernanda Lima",
    message: "Comecei do zero e hoje tenho uma renda extra de R$2.500 por mês!",
    time: "15 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 106,
    name: "Gabriela Alves",
    message: "Minhas amigas não acreditam que faço esses doces sem ir ao fogo!",
    time: "20 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 107,
    name: "Helena Martins",
    message: "Vendi 45 potes de mousse no primeiro dia usando as receitas!",
    time: "25 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 108,
    name: "Isabela Ferreira",
    message: "Já paguei todas as minhas dívidas com a venda de doces em casa!",
    time: "30 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 109,
    name: "Juliana Pereira",
    message: "Meu brigadeiro gourmet virou sensação no Instagram!",
    time: "35 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 110,
    name: "Karina Souza",
    message: "Consegui comprar meu carro com a venda de doces sem forno!",
    time: "40 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 111,
    name: "Larissa Campos",
    message: "Meus clientes sempre voltam para comprar mais, é incrível!",
    time: "45 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 112,
    name: "Mariana Silva",
    message: "Estou vendendo para festas e eventos com apenas 1 mês de experiência!",
    time: "50 min",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]
